global:
  scrape_interval: 15s # По умолчанию собираем метрики каждые 15 секунд

scrape_configs:
  - job_name: 'cinematique-app'
    static_configs:
      - targets: ['host.docker.internal:8080'] # Цель для сбора метрик с Go приложения
